### ISSUE TITLE
Autocmd to call glyph_palette#apply not working on draw open

### ISSUE THREAD

**Issue by patstockwell** [lambdalisue/glyph-palette.vim#14]
Hi 👋 , thanks for this great plugin! This might not be a plugin problem, but a user error 😅 Hoping you can point me in the right direction. I am having an issue with the recommended `autocmd` not working as expected.
```vim
augroup my-glyph-palette
  autocmd!
  autocmd FileType fern call glyph_palette#apply()
augroup END
```
When I load a _Fern_ buffer using either `:Fern` or `vim .` from the command line, I get glyph icons in just one colour. When I move my cursor to a different window, and then move back to the fern window, the glyph icons change to use highlighted colours. This tells me that the autocmd is there, but perhaps is happening out of order, or too early in some cases.

Have you seen this behavour before? Are you able to suggest an fixes? Thanks for your time 🙏 
<img width="922" alt="Screen Shot 2020-11-01 at 3 11 14 pm" src="https://user-images.githubusercontent.com/14284552/97794957-922a2c00-1c54-11eb-8134-1258bdff3e6e.png">
<img width="922" alt="Screen Shot 2020-11-01 at 3 11 18 pm" src="https://user-images.githubusercontent.com/14284552/97794959-98200d00-1c54-11eb-8245-8b0573a1a686.png">

**Comment by lambdalisue** [comment]
Approx. 10 days ago. I've put https://github.com/lambdalisue/glyph-palette.vim/commit/9da4d62ec2d9057b923581e906a4231de3150df9 and I guess that commit fix your issue so make sure that you are using the latest glyph-palette.vim

**Comment by patstockwell** [comment]
Thanks so much. I'll try it out again! 🙏
